apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # 여러분의 image 주소를 입력해주세요.
          image: krmp-d2hub-idock.9rum.cc/dev-test/repo_13d4efd6d916
          env:
            - name: PROJECT_ENV
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: PROJECT_ENV
            - name: NEXT_PUBLIC_PROJECT_ENV
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: NEXT_PUBLIC_PROJECT_ENV
            - name: NEXT_PUBLIC_API_URL
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: NEXT_PUBLIC_API_URL
            - name: NEXT_PUBLIC_API_KAKAO_URL
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: NEXT_PUBLIC_API_KAKAO_URL
            - name: NEXT_PUBLIC_API_KAKAO_JS_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: NEXT_PUBLIC_API_KAKAO_JS_KEY
            - name: NEXT_PUBLIC_API_KAKAO_REST_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: NEXT_PUBLIC_API_KAKAO_REST_KEY
            - name: NEXT_PUBLIC_API_MOCKING_STATUS
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: NEXT_PUBLIC_API_MOCKING_STATUS
            - name: NEXT_PUBLIC_API_MOCKING_PORT
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: NEXT_PUBLIC_API_MOCKING_PORT
            - name: NEXT_PUBLIC_API_MOCKING_URL
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: NEXT_PUBLIC_API_MOCKING_URL
            - name: NEXT_PUBLIC_API_WORLD_URL
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: NEXT_PUBLIC_API_WORLD_URL
            - name: NEXT_PUBLIC_API_WORLD_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-env
                  key: NEXT_PUBLIC_API_WORLD_KEY
