export const IconName = {
  ["ArrowRight"]: "ArrowRight",
  ["CaretDown"]: "CaretDown",
  ["CaretUp"]: "CaretUp",
  ["CheckCircle"]: "CheckCircle",
  ["CheckCircleFilled"]: "CheckCircleFilled",
  ["Close"]: "Close",
  ["CloseCircle"]: "CloseCircle",
  ["CloseCircleFilled"]: "CloseCircleFilled",
  ["Environment"]: "Environment",
  ["ExclamationCircle"]: "ExclamationCircle",
  ["ExclamationCircleFilled"]: "ExclamationCircleFilled",
  ["InfoCircle"]: "InfoCircle",
  ["InfoCircleFilled"]: "InfoCircleFilled",
  ["Left"]: "Left",
  ["LineChart"]: "LineChart",
  ["Loading"]: "Loading",
  ["Mail"]: "Mail",
  ["Menu"]: "Menu",
  ["Picture"]: "Picture",
  ["Pin"]: "Pin",
  ["Reload"]: "Reload",
  ["Right"]: "Right",
  ["Search"]: "Search",
  ["User"]: "User",
  ["Warning"]: "Warning",
} as const

export type IconName = (typeof IconName)[keyof typeof IconName]
